DROP PROCEDURE IF EXISTS feguslocal.generar_operaciones_deudor CASCADE;
CREATE PROCEDURE feguslocal.generar_operaciones_deudor(IN pid_load_local bigint, IN p_deudor feguslocal.deudores_type, IN p_cantidad integer)
    LANGUAGE plpgsql
    AS $$
BEGIN

	FOR i IN 1..p_cantidad LOOP

		INSERT INTO feguslocal.operacionescredito(
	"id_load_local", "TipoOperacionSFN", "TipoPersonaDeudor", "IdDeudor", "IdOperacionCredito", "IdLineaCredito", "IndicadorOperacionModificada", "IndicadorPresentaCodeudores", "TipoEnfoque", "TipoSegmento", "CodigoEtapa", "CodigoCategoriaRiesgo", "TasaIncumplimiento", "LGDMinimoCombinado", "LGDPromedio", "LGDRegulatorio", "TipoOperacion", "TipoCatalogoSUGEF", "CodigoPaisDestinoCredito", "CodigoProvinciaDestinoCredito", "CodigoCantonDestinoCredito", "CodigoDistritoDestinoCredito", "CodigoProvinciaDependenciaCredito", "CodigoCantonDependenciaCredito", "TipoCarteraCrediticia", "TipoEstadoOperacionCrediticia", "DiasMaximaMorosidad", "MontoFormalizadoOperacionCrediticia", "TipoMonedaOperacion", "MontoOperacionAutorizado", "CuentaContablePrincipal", "SaldoPrincipalOperacionCrediticia", "CuentaContablePrincipalConDepositoPrevio", "SaldoPrincipalConDepositoPrevio", "CuentaContableProductosPorCobrar", "SaldoProductosPorCobrar", "CuentaContablePorDesembolsarConCompromiso", "SaldoPorDesembolsarConCompromiso", "CuentaContableComisiones", "SaldoComisionesOperacionesContingentes", "CuentaContableSaldoPendienteUtilizacionSinCompromiso", "SaldoPendienteUtilizacionSinCompromiso", "MontoDesembolsado", "FechaFormalizacion", "FechaVencimiento", "EAD", "SaldoOperacionSegmentacion", "TipoFrecuenciaPagoActualPrincipal", "TipoFrecuenciaPagoActualIntereses", "FechaVencimientoPeriodoGraciaPrincipal", "TasaLey7472", "TasaInteresNominalVigente", "IndicadorTipoTasa", "FactorDeTiempoCalculoIntereses", "IndicadorFormaPagoVigentePrincipal", "IndicadorFormaPagoVigenteIntereses", "FechaCorteOperacion", "FechaProximoPagoPrincipal", "FechaProximoPagoIntereses", "FechaAmortizacionHasta", "FechaInteresHasta", "FechaPagoPactadoPrincipal", "FechaPagoPactadoIntereses", "PlazoOperacionDias", "TipoCuotaPrincipal", "MontoCuotaPrincipalActual", "MontoCuotaInteresesActual", "IndicadorOperacionNueva", "MontoRecuperacionPrincipal", "MontoOtrosAumentosDePrincipal", "MontoOtrasDisminucionesDePrincipal", "IndicadorBacktoBack", "IndicadorCreditoSindicado", "IndicadorOperacionEspecial", "TipoMotivoOperacionEspecial", "CodigoClausulaLimiteCredito", "FechaCambioTipoTasa", "TipoFrecuenciaAjusteTasaInteresVariable", "TipoParametroReferenciaTasaInteresVariable", "PorcentajeComponenteVariableTasaInteresVariable", "PorcentajeComponenteFijoTasaInteresVariable", "LimiteInferiorTasaInteresVariable", "LimiteSuperiorTasaInteresVariable", "MontoEstimacionEspecifica", "MontoEstimacionAvales", "TipoProgramaAutorizadoSBD", "IndicadorCreditoGrupalSolidarioSBD", "TipoSectorPrioritarioDeudorSBD", "IdFondeadorSBD", "TipoPersonaIdFondeadorSBD", "IndicadorOperacionCedidaEnGarantia", "PorcentajePonderadorSPD", "PorcentajePonderadorSPC", "PorcentajeIndicadorLTV", "IndicadorCambioClimatico", "TipoClasificacionRiesgoClimatico", "TipoMetodolog├¡aClim├ítico", "TipoPotencialidadImpactoClimatico", "updated_at_utc")
	VALUES (
    pid_load_local ,  -- "id_load_local"	
    (ARRAY[1,3,4,5,6])[floor(random() * 5 + 1)] ,  -- "TipoOperacionSFN"
    p_deudor.TipoPersonaDeudor ,  -- "TipoPersonaDeudor"
    p_deudor.IdDeudor ,  -- "IdDeudor"
    feguslocal.generar_id_fegus('OPER','seq_operacion') ,  -- "IdOperacionCredito"
    null ,  -- "IdLineaCredito"
    null ,  -- "IndicadorOperacionModificada"
    null ,  -- "IndicadorPresentaCodeudores"
    null ,  -- "TipoEnfoque"
    null ,  -- "TipoSegmento"
    null ,  -- "CodigoEtapa"
    null ,  -- "CodigoCategoriaRiesgo"
    null ,  -- "TasaIncumplimiento"
    null ,  -- "LGDMinimoCombinado"
    null ,  -- "LGDPromedio"
    null ,  -- "LGDRegulatorio"
    (ARRAY[1,2,3,4,5,6,7,8,9])[floor(random() * 9 + 1)] ,  -- "TipoOperacion"
    14 ,  -- "TipoCatalogoSUGEF"
    (ARRAY[1,2,3,4,5,6,7,8])[floor(random() * 8 + 1)] ,  -- "CodigoPaisDestinoCredito"
    (ARRAY[1,2,3,4,5,6,7,8])[floor(random() * 8 + 1)] ,  -- "CodigoProvinciaDestinoCredito"
    (ARRAY[1,2,3,4,5,6,7,8])[floor(random() * 8 + 1)] ,  -- "CodigoCantonDestinoCredito"
    (ARRAY[1,2,3,4,5,6,7,8])[floor(random() * 8 + 1)] ,  -- "CodigoDistritoDestinoCredito"
    (ARRAY[1,2,3,4,5,6,7,8])[floor(random() * 8 + 1)] ,  -- "CodigoProvinciaDependenciaCredito"
    (ARRAY[1,2,3,4,5,6,7,8])[floor(random() * 8 + 1)] ,  -- "CodigoCantonDependenciaCredito"
    (ARRAY[0,1,2,3,4,5,6,7,8,9,10,11])[floor(random() * 11 + 1)] ,  -- "TipoCarteraCrediticia"
    (ARRAY[1,2,3,4,5,6])[floor(random() * 6 + 1)] ,  -- "TipoEstadoOperacionCrediticia"
    floor(random() * 201)::int ,  -- "DiasMaximaMorosidad"
    round((random()*1000000)::numeric, 2) ,  -- "MontoFormalizadoOperacionCrediticia"
    (ARRAY[1,2])[floor(random() * 2 + 1)] ,  -- "TipoMonedaOperacion"
    round((random()*1000000)::numeric, 2) ,  -- "MontoOperacionAutorizado"
    (ARRAY[13131101,13401200,13132125,13233201,13231203,13332125,13131104,13331102,13131203,13331203,13231104,13231204,13131201,13131102,13231101,13131103,13133101,13232125,13233101,13131110,13131210,13231202,13136101,13333201,13331202,13331103,13401100,13133201,13231102,13231201,13333101,13231103,13402100,13402200,13132134,13131204,13131202])[floor(random() * 38 + 1)] ,  -- "CuentaContablePrincipal"
    round((random()*1000000)::numeric, 2) ,  -- "SaldoPrincipalOperacionCrediticia"
    null ,  -- "CuentaContablePrincipalConDepositoPrevio"
    0 ,  -- "SaldoPrincipalConDepositoPrevio"
    (ARRAY[13831101,13832134,13831110,13831102,13831210,13831103,13831202,13836101,13833101,13831204,13833201,13831203,13831104,13831201,13832125])[floor(random() * 38 + 1)] ,  -- "CuentaContableProductosPorCobrar"
    round((random()*1000000)::numeric, 2) ,  -- "SaldoProductosPorCobrar"
    (ARRAY[61502200,61901200,61901100])[floor(random() * 3 + 1)] ,  -- "CuentaContablePorDesembolsarConCompromiso"
    round((random()*1000000)::numeric, 2) ,  -- "SaldoPorDesembolsarConCompromiso"
    null ,  -- "CuentaContableComisiones"
    0 ,  -- "SaldoComisionesOperacionesContingentes"
    null ,  -- "CuentaContableSaldoPendienteUtilizacionSinCompromiso"
    0 ,  -- "SaldoPendienteUtilizacionSinCompromiso"
    round((random()*1000000)::numeric, 2) ,  -- "MontoDesembolsado"
    (CURRENT_DATE - (random()*1825)::int) ,  -- "FechaFormalizacion"
    (CURRENT_DATE - (random()*1825)::int) ,  -- "FechaVencimiento"
    round((random()*1000000)::numeric, 2) ,  -- "EAD"
    round((random()*1000000)::numeric, 2) ,  -- "SaldoOperacionSegmentacion"
    (ARRAY[2,3,4])[floor(random() * 3 + 1)] ,  -- "TipoFrecuenciaPagoActualPrincipal"
    (ARRAY[2,3,4])[floor(random() * 3 + 1)] ,  -- "TipoFrecuenciaPagoActualIntereses"
    null ,  -- "FechaVencimientoPeriodoGraciaPrincipal"
    round((random() * 999)::numeric, 2) ,  -- "TasaLey7472"
    round((random() * 999)::numeric, 2) ,  -- "TasaInteresNominalVigente"
    (ARRAY['V','F'])[floor(random() * 2 + 1)] ,  -- "IndicadorTipoTasa"
    4 ,  -- "FactorDeTiempoCalculoIntereses"
    'V' ,  -- "IndicadorFormaPagoVigentePrincipal"
    'V' ,  -- "IndicadorFormaPagoVigenteIntereses"
    (CURRENT_DATE - (random()*1825)::int) ,  -- "FechaCorteOperacion"
    (CURRENT_DATE - (random()*1825)::int) ,  -- "FechaProximoPagoPrincipal"
    (CURRENT_DATE - (random()*1825)::int) ,  -- "FechaProximoPagoIntereses"
    (CURRENT_DATE - (random()*1825)::int) ,  -- "FechaAmortizacionHasta"
    (CURRENT_DATE - (random()*1825)::int) ,  -- "FechaInteresHasta"
    (CURRENT_DATE - (random()*1825)::int) ,  -- "FechaPagoPactadoPrincipal"
    (CURRENT_DATE - (random()*1825)::int) ,  -- "FechaPagoPactadoIntereses"
    540 ,  -- "PlazoOperacionDias"
    4 ,  -- "TipoCuotaPrincipal"
    round((random()*1000000)::numeric, 2) ,  -- "MontoCuotaPrincipalActual"
    round((random()*1000000)::numeric, 2) ,  -- "MontoCuotaInteresesActual"
    'N' ,  -- "IndicadorOperacionNueva"
    round((random()*1000000)::numeric, 2) ,  -- "MontoRecuperacionPrincipal"
    round((random()*1000000)::numeric, 2) ,  -- "MontoOtrosAumentosDePrincipal"
    round((random()*1000000)::numeric, 2) ,  -- "MontoOtrasDisminucionesDePrincipal"
    'N' ,  -- "IndicadorBacktoBack"
    'N' ,  -- "IndicadorCreditoSindicado"
    'N' ,  -- "IndicadorOperacionEspecial"
    (ARRAY[null,1,2])[floor(random() * 4 + 1)] ,  -- "TipoMotivoOperacionEspecial"
    0 ,  -- "CodigoClausulaLimiteCredito"
    (CURRENT_DATE - (random()*1825)::int) ,  -- "FechaCambioTipoTasa"
    (ARRAY[2,3,4])[floor(random() * 3 + 1)] ,  -- "TipoFrecuenciaAjusteTasaInteresVariable"
    4 ,  -- "TipoParametroReferenciaTasaInteresVariable"
    round((random() * 999)::numeric, 2) ,  -- "PorcentajeComponenteVariableTasaInteresVariable"
    round((random() * 999)::numeric, 2) ,  -- "PorcentajeComponenteFijoTasaInteresVariable"
    round((random() * 999)::numeric, 2) ,  -- "LimiteInferiorTasaInteresVariable"
    round((random() * 999)::numeric, 2) ,  -- "LimiteSuperiorTasaInteresVariable"
    round((random()*1000000)::numeric, 2) ,  -- "MontoEstimacionEspecifica"
    round((random()*1000000)::numeric, 2) ,  -- "MontoEstimacionAvales"
    30019 ,  -- "TipoProgramaAutorizadoSBD"
    0 ,  -- "IndicadorCreditoGrupalSolidarioSBD"
    0 ,  -- "TipoSectorPrioritarioDeudorSBD"
    NULL ,  -- "IdFondeadorSBD"
    NULL ,  -- "TipoPersonaIdFondeadorSBD"
    'N' ,  -- "IndicadorOperacionCedidaEnGarantia"
    round((random() * 999)::numeric, 2) ,  -- "PorcentajePonderadorSPD"
    round((random() * 999)::numeric, 2) ,  -- "PorcentajePonderadorSPC"
    round((random() * 999)::numeric, 2) ,  -- "PorcentajeIndicadorLTV"
    'N' ,  -- "IndicadorCambioClimatico"
    (ARRAY[1,2,3])[floor(random() * 3 + 1)] ,  -- "TipoClasificacionRiesgoClimatico"
    (ARRAY[0,1,2])[floor(random() * 3 + 1)] ,  -- "TipoMetodolog├¡aClim├ítico"
    (ARRAY[0,1,2,3,4,5,6,7,8,9])[floor(random() * 10 + 1)] ,  -- "TipoPotencialidadImpactoClimatico"
    (CURRENT_DATE - (random()*1825)::int)   -- "updated_at_utc"    
);

	
		--RAISE NOTICE 'Num: %, Procesando IdDeudor: %', i,p_deudor.IdDeudor;
	END LOOP;
    
END 
$$;
