-- Table: fegusdata.operacionescredito

-- DROP TABLE IF EXISTS fegusdata.operacionescredito;

CREATE TABLE IF NOT EXISTS fegusdata.operacionescredito
(
    id_cliente integer NOT NULL,
	id_load bigint NOT NULL,
	session_id uuid NOT NULL,
	seq bigint NOT NULL,
    tipooperacionsfn numeric(1,0) NOT NULL,
    tipopersonadeudor numeric(2,0) NOT NULL,
    iddeudor character varying(30) COLLATE pg_catalog."default" NOT NULL,
    idoperacioncredito character varying(25) COLLATE pg_catalog."default" NOT NULL,
    idlineacredito character varying(25) COLLATE pg_catalog."default",
    indicadoroperacionmodificada character varying(1) COLLATE pg_catalog."default",
    indicadorpresentacodeudores character varying(1) COLLATE pg_catalog."default",
    tipoenfoque numeric(2,0),
    tiposegmento numeric(2,0),
    codigoetapa numeric(2,0),
    codigocategoriariesgo numeric(2,0),
    tasaincumplimiento numeric(5,2),
    lgdminimocombinado numeric(5,2),
    lgdpromedio numeric(5,2),
    lgdregulatorio numeric(5,2),
    tipooperacion numeric(3,0) NOT NULL,
    tipocatalogosugef numeric(3,0) NOT NULL,
    codigopaisdestinocredito character varying(4) COLLATE pg_catalog."default",
    codigoprovinciadestinocredito numeric(2,0),
    codigocantondestinocredito numeric(2,0),
    codigodistritodestinocredito numeric(4,0),
    codigoprovinciadependenciacredito numeric(2,0),
    codigocantondependenciacredito numeric(2,0),
    tipocarteracrediticia numeric(2,0) NOT NULL,
    tipoestadooperacioncrediticia numeric(3,0),
    diasmaximamorosidad numeric(4,0) NOT NULL,
    montoformalizadooperacioncrediticia numeric(22,2),
    tipomonedaoperacion numeric(6,0) NOT NULL,
    montooperacionautorizado numeric(22,2) NOT NULL,
    cuentacontableprincipal numeric(15,0),
    saldoprincipaloperacioncrediticia numeric NOT NULL,
    cuentacontableprincipalcondepositoprevio numeric(15,0),
    saldoprincipalcondepositoprevio numeric(22,2) NOT NULL,
    cuentacontableproductosporcobrar numeric(15,0),
    saldoproductosporcobrar numeric(22,2) NOT NULL,
    cuentacontablepordesembolsarconcompromiso numeric(15,0),
    saldopordesembolsarconcompromiso numeric(22,2) NOT NULL,
    cuentacontablecomisiones numeric(15,0),
    saldocomisionesoperacionescontingentes numeric(22,2) NOT NULL,
    cuentacontablesaldopendienteutilizacionsincompromiso numeric(15,0),
    saldopendienteutilizacionsincompromiso numeric(22,2),
    montodesembolsado numeric(22,2) NOT NULL,
    fechaformalizacion date NOT NULL,
    fechavencimiento date NOT NULL,
    ead numeric(22,2) NOT NULL,
    saldooperacionsegmentacion numeric(22,2),
    tipofrecuenciapagoactualprincipal numeric(2,0),
    tipofrecuenciapagoactualintereses numeric(2,0),
    fechavencimientoperiodograciaprincipal date,
    tasaley7472 numeric(10,7),
    tasainteresnominalvigente numeric(5,2),
    indicadortipotasa character varying(2) COLLATE pg_catalog."default",
    factordetiempocalculointereses character varying(1) COLLATE pg_catalog."default",
    indicadorformapagovigenteprincipal character varying(1) COLLATE pg_catalog."default",
    indicadorformapagovigenteintereses character varying(1) COLLATE pg_catalog."default",
    fechacorteoperacion date,
    fechaproximopagoprincipal date,
    fechaproximopagointereses date,
    fechaamortizacionhasta date,
    fechaintereshasta date,
    fechapagopactadoprincipal date,
    fechapagopactadointereses date,
    plazooperaciondias numeric(6,0) NOT NULL,
    tipocuotaprincipal numeric(2,0),
    montocuotaprincipalactual numeric(22,2),
    montocuotainteresesactual numeric(22,2),
    indicadoroperacionnueva character varying(1) COLLATE pg_catalog."default",
    montorecuperacionprincipal numeric(22,2) NOT NULL,
    montootrosaumentosdeprincipal numeric(22,2) NOT NULL,
    montootrasdisminucionesdeprincipal numeric(22,2) NOT NULL,
    indicadorbacktoback character varying(1) COLLATE pg_catalog."default" NOT NULL,
    indicadorcreditosindicado character varying(1) COLLATE pg_catalog."default" NOT NULL,
    indicadoroperacionespecial character varying(1) COLLATE pg_catalog."default" NOT NULL,
    tipomotivooperacionespecial numeric(3,0),
    codigoclausulalimitecredito numeric(2,0),
    fechacambiotipotasa date,
    tipofrecuenciaajustetasainteresvariable numeric(2,0),
    tipoparametroreferenciatasainteresvariable numeric(3,0),
    porcentajecomponentevariabletasainteresvariable numeric(5,2),
    porcentajecomponentefijotasainteresvariable numeric(5,2),
    limiteinferiortasainteresvariable numeric(5,2),
    limitesuperiortasainteresvariable numeric(5,2),
    montoestimacionespecifica numeric(22,2),
    montoestimacionavales numeric(22,2),
    tipoprogramaautorizadosbd numeric(5,0) NOT NULL,
    indicadorcreditogrupalsolidariosbd numeric(1,0) NOT NULL,
    tiposectorprioritariodeudorsbd numeric(2,0) NOT NULL,
    idfondeadorsbd character varying(30) COLLATE pg_catalog."default",
    tipopersonaidfondeadorsbd numeric(2,0),
    indicadoroperacioncedidaengarantia character varying(1) COLLATE pg_catalog."default" NOT NULL,
    porcentajeponderadorspd numeric(5,2) NOT NULL,
    porcentajeponderadorspc numeric(5,2) NOT NULL,
    porcentajeindicadorltv numeric(5,2),
    indicadorcambioclimatico character varying(1) COLLATE pg_catalog."default" NOT NULL,
    tipoclasificacionriesgoclimatico numeric(2,0),
    tipometodologiaclimatica numeric(2,0),
    tipopotencialidadimpactoclimatico numeric(2,0),
    created_at_utc timestamp without time zone NOT NULL DEFAULT now(),
    updated_at_utc timestamp without time zone,
    CONSTRAINT pk_operaciones PRIMARY KEY (id_cliente, id_load, session_id, idoperacioncredito)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS fegusdata.operacionescredito
    OWNER to postgres;


CREATE INDEX IF NOT EXISTS ix_operaciones_idx1
ON fegusdata.operacionescredito (
    id_cliente,
    id_load,
    idoperacioncredito       
);     