CREATE TABLE "FegusData".OperacionesCredito (
    "Id_Cliente" INTEGER NOT NULL,
    "TipoOperacionSFN" NUMERIC(1) NOT NULL,
    "TipoPersonaDeudor" NUMERIC(2) NOT NULL,
    "IdDeudor" VARCHAR(30) NOT NULL,
    "IdOperacionCredito" VARCHAR(25) NOT NULL,
    "IdLineaCredito" VARCHAR(25) NULL,
    "IndicadorOperacionModificada" VARCHAR(1) NOT NULL,
    "IndicadorPresentaCodeudores" VARCHAR(1) NOT NULL,
    "TipoEnfoque" NUMERIC(2) NOT NULL,
    "TipoSegmento" NUMERIC(2) NOT NULL,
    "CodigoEtapa" NUMERIC(2) NOT NULL,
    "CodigoCategoriaRiesgo" NUMERIC(2) NOT NULL,
    "TasaIncumplimiento" NUMERIC(5,2) NOT NULL,
    "LGDMinimoCombinado" NUMERIC(5,2) NULL,
    "LGDPromedio" NUMERIC(5,2) NULL,
    "LGDRegulatorio" NUMERIC(5,2) NULL,
    "TipoOperacion" NUMERIC(3) NOT NULL,
    "TipoCatalogoSUGEF" NUMERIC(3) NOT NULL,
    "CodigoPaisDestinoCredito" VARCHAR(4) NULL,
    "CodigoProvinciaDestinoCredito" NUMERIC(2) NULL,
    "CodigoCantonDestinoCredito" NUMERIC(2) NULL,
    "CodigoDistritoDestinoCredito" NUMERIC(4) NULL,
    "CodigoProvinciaDependenciaCredito" NUMERIC(2) NULL,
    "CodigoCantonDependenciaCredito" NUMERIC(2) NULL,
    "TipoCarteraCrediticia" NUMERIC(2) NOT NULL,
    "TipoEstadoOperacionCrediticia" NUMERIC(3) NULL,
    "DiasMaximaMorosidad" NUMERIC(4) NOT NULL,
    "MontoFormalizadoOperacionCrediticia" NUMERIC(22,2) NULL,
    "TipoMonedaOperacion" NUMERIC(6) NOT NULL,
    "MontoOperacionAutorizado" NUMERIC(22,2) NOT NULL,
    "CuentaContablePrincipal" NUMERIC(15) NULL,
    "SaldoPrincipalOperacionCrediticia" NUMERIC NOT NULL,
    "CuentaContablePrincipalConDepositoPrevio" NUMERIC(15) NULL,
    "SaldoPrincipalConDepositoPrevio" NUMERIC(22,2) NOT NULL,
    "CuentaContableProductosPorCobrar" NUMERIC(15) NULL,
    "SaldoProductosPorCobrar" NUMERIC(22,2) NOT NULL,
    "CuentaContablePorDesembolsarConCompromiso" NUMERIC(15) NULL,
    "SaldoPorDesembolsarConCompromiso" NUMERIC(22,2) NOT NULL,
    "CuentaContableComisiones" NUMERIC(15) NULL,
    "SaldoComisionesOperacionesContingentes" NUMERIC(22,2) NOT NULL,
    "CuentaContableSaldoPendienteUtilizacionSinCompromiso" NUMERIC(15) NULL,
    "SaldoPendienteUtilizacionSinCompromiso" NUMERIC(22,2) NULL,
    "MontoDesembolsado" NUMERIC(22,2) NOT NULL,
    "FechaFormalizacion" DATE NOT NULL,
    "FechaVencimiento" DATE NOT NULL,
    "EAD" NUMERIC(22,2) NOT NULL,
    "SaldoOperacionSegmentacion" NUMERIC(22,2) NULL,
    "TipoFrecuenciaPagoActualPrincipal" NUMERIC(2) NULL,
    "TipoFrecuenciaPagoActualIntereses" NUMERIC(2) NULL,
    "FechaVencimientoPeriodoGraciaPrincipal" DATE NULL,
    "TasaLey7472" NUMERIC(10,7) NULL,
    "TasaInteresNominalVigente" NUMERIC(5,2) NULL,
    "IndicadorTipoTasa" VARCHAR(2) NULL,
    "FactorDeTiempoCalculoIntereses" VARCHAR(1) NULL,
    "IndicadorFormaPagoVigentePrincipal" VARCHAR(1) NULL,
    "IndicadorFormaPagoVigenteIntereses" VARCHAR(1) NULL,
    "FechaCorteOperacion" DATE NULL,
    "FechaProximoPagoPrincipal" DATE NULL,
    "FechaProximoPagoIntereses" DATE NULL,
    "FechaAmortizacionHasta" DATE NULL,
    "FechaInteresHasta" DATE NULL,
    "FechaPagoPactadoPrincipal" DATE NULL,
    "FechaPagoPactadoIntereses" DATE NULL,
    "PlazoOperacionDias" NUMERIC(6) NOT NULL,
    "TipoCuotaPrincipal" NUMERIC(2) NULL,
    "MontoCuotaPrincipalActual" NUMERIC(22,2) NULL,
    "MontoCuotaInteresesActual" NUMERIC(22,2) NULL,
    "IndicadorOperacionNueva" VARCHAR(1) NOT NULL,
    "MontoRecuperacionPrincipal" NUMERIC(22,2) NOT NULL,
    "MontoOtrosAumentosDePrincipal" NUMERIC(22,2) NOT NULL,
    "MontoOtrasDisminucionesDePrincipal" NUMERIC(22,2) NOT NULL,
    "IndicadorBacktoBack" VARCHAR(1) NOT NULL,
    "IndicadorCreditoSindicado" VARCHAR(1) NOT NULL,
    "IndicadorOperacionEspecial" VARCHAR(1) NOT NULL,
    "TipoMotivoOperacionEspecial" NUMERIC(3) NULL,
    "CodigoClausulaLimiteCredito" NUMERIC(2) NULL,
    "FechaCambioTipoTasa" DATE NULL,
    "TipoFrecuenciaAjusteTasaInteresVariable" NUMERIC(2) NULL,
    "TipoParametroReferenciaTasaInteresVariable" NUMERIC(3) NULL,
    "PorcentajeComponenteVariableTasaInteresVariable" NUMERIC(5,2) NULL,
    "PorcentajeComponenteFijoTasaInteresVariable" NUMERIC(5,2) NULL,
    "LimiteInferiorTasaInteresVariable" NUMERIC(5,2) NULL,
    "LimiteSuperiorTasaInteresVariable" NUMERIC(5,2) NULL,
    "MontoEstimacionEspecifica" NUMERIC(22,2) NULL,
    "MontoEstimacionAvales" NUMERIC(22,2) NULL,
    "TipoProgramaAutorizadoSBD" NUMERIC(5) NOT NULL,
    "IndicadorCreditoGrupalSolidarioSBD" NUMERIC(1) NOT NULL,
    "TipoSectorPrioritarioDeudorSBD" NUMERIC(2) NOT NULL,
    "IdFondeadorSBD" VARCHAR(30) NULL,
    "TipoPersonaIdFondeadorSBD" NUMERIC(2) NULL,
    "IndicadorOperacionCedidaEnGarantia" VARCHAR(1) NOT NULL,
    "PorcentajePonderadorSPD" NUMERIC(5,2) NOT NULL,
    "PorcentajePonderadorSPC" NUMERIC(5,2) NOT NULL,
    "PorcentajeIndicadorLTV" NUMERIC(5,2) NULL,
    "IndicadorCambioClimatico" VARCHAR(1) NOT NULL,
    "TipoClasificacionRiesgoClimatico" NUMERIC(2) NULL,
    "TipoMetodologíaClimático" NUMERIC(2) NULL,
    "TipoPotencialidadImpactoClimatico" NUMERIC(2) NULL,
    "FechaUltGestion" DATE NOT NULL,
    "CodUsuarioUltGestion" VARCHAR(50) NOT NULL,
    CONSTRAINT PK_OperacionesCredito PRIMARY KEY ("Id_Cliente", "IdOperacionCredito")
);
