-- Target: ConnectionStringAzure (Azure PostgreSQL)
-- Transfers raw operaciones de credito payload from fegusconfig staging to fegusdata.operacionescredito.
-- Idempotent via ON CONFLICT DO UPDATE.

CREATE OR REPLACE FUNCTION fegusdata.fn_load_operacionescredito_from_raw(
    p_id_cliente integer,
    p_id_load    bigint
)
RETURNS TABLE(pqty integer, psqlcode text, psqlmessage text)
LANGUAGE plpgsql
AS $$
DECLARE
    v_qty integer := 0;
BEGIN
    INSERT INTO fegusdata.operacionescredito (
        id_cliente, id_load, session_id, seq,
        tipooperacionsfn, tipopersonadeudor, iddeudor, idoperacioncredito,
        idlineacredito, indicadoroperacionmodificada, indicadorpresentacodeudores,
        tipoenfoque, tiposegmento, codigoetapa, codigocategoriariesgo,
        tasaincumplimiento, lgdminimocombinado, lgdpromedio, lgdregulatorio,
        tipooperacion, tipocatalogosugef,
        codigopaisdestinocredito, codigoprovinciadestinocredito, codigocantondestinocredito,
        codigodistritodestinocredito, codigoprovinciadependenciacredito, codigocantondependenciacredito,
        tipocarteracrediticia, tipoestadooperacioncrediticia, diasmaximamorosidad,
        montoformalizadooperacioncrediticia, tipomonedaoperacion, montooperacionautorizado,
        cuentacontableprincipal, saldoprincipaloperacioncrediticia,
        cuentacontableprincipalcondepositoprevio, saldoprincipalcondepositoprevio,
        cuentacontableproductosporcobrar, saldoproductosporcobrar,
        cuentacontablepordesembolsarconcompromiso, saldopordesembolsarconcompromiso,
        cuentacontablecomisiones, saldocomisionesoperacionescontingentes,
        cuentacontablesaldopendienteutilizacionsincompromiso, saldopendienteutilizacionsincompromiso,
        montodesembolsado, fechaformalizacion, fechavencimiento, ead,
        saldooperacionsegmentacion, tipofrecuenciapagoactualprincipal, tipofrecuenciapagoactualintereses,
        fechavencimientoperiodograciaprincipal, tasaley7472, tasainteresnominalvigente,
        indicadortipotasa, factordetiempocalculointereses,
        indicadorformapagovigenteprincipal, indicadorformapagovigenteintereses,
        fechacorteoperacion, fechaproximopagoprincipal, fechaproximopagointereses,
        fechaamortizacionhasta, fechaintereshasta, fechapagopactadoprincipal, fechapagopactadointereses,
        plazooperaciondias, tipocuotaprincipal, montocuotaprincipalactual, montocuotainteresesactual,
        indicadoroperacionnueva, montorecuperacionprincipal, montootrosaumentosdeprincipal,
        montootrasdisminucionesdeprincipal, indicadorbacktoback, indicadorcreditosindicado,
        indicadoroperacionespecial, tipomotivooperacionespecial, codigoclausulalimitecredito,
        fechacambiotipotasa, tipofrecuenciaajustetasainteresvariable,
        tipoparametroreferenciatasainteresvariable, porcentajecomponentevariabletasainteresvariable,
        porcentajecomponentefijotasainteresvariable, limiteinferiortasainteresvariable,
        limitesuperiortasainteresvariable, montoestimacionespecifica, montoestimacionavales,
        tipoprogramaautorizadosbd, indicadorcreditogrupalsolidariosbd, tiposectorprioritariodeudorsbd,
        idfondeadorsbd, tipopersonaidfondeadorsbd, indicadoroperacioncedidaengarantia,
        porcentajeponderadorspd, porcentajeponderadorspc, porcentajeindicadorltv,
        indicadorcambioclimatico, tipoclasificacionriesgoclimatico, tipometodologiaclimatica,
        tipopotencialidadimpactoclimatico,
        created_at_utc, updated_at_utc
    )
    SELECT
        r.id_cliente, r.id_load, r.session_id, r.seq,
        (r.payload->>'tipooperacionsfn')::numeric(1,0),
        (r.payload->>'tipopersonadeudor')::numeric(2,0),
        r.payload->>'iddeudor',
        r.payload->>'idoperacioncredito',
        r.payload->>'idlineacredito',
        r.payload->>'indicadoroperacionmodificada',
        r.payload->>'indicadorpresentacodeudores',
        (r.payload->>'tipoenfoque')::numeric(2,0),
        (r.payload->>'tiposegmento')::numeric(2,0),
        (r.payload->>'codigoetapa')::numeric(2,0),
        (r.payload->>'codigocategoriariesgo')::numeric(2,0),
        (r.payload->>'tasaincumplimiento')::numeric(5,2),
        (r.payload->>'lgdminimocombinado')::numeric(5,2),
        (r.payload->>'lgdpromedio')::numeric(5,2),
        (r.payload->>'lgdregulatorio')::numeric(5,2),
        (r.payload->>'tipooperacion')::numeric(3,0),
        (r.payload->>'tipocatalogosugef')::numeric(3,0),
        r.payload->>'codigopaisdestinocredito',
        (r.payload->>'codigoprovinciadestinocredito')::numeric(2,0),
        (r.payload->>'codigocantondestinocredito')::numeric(2,0),
        (r.payload->>'codigodistritodestinocredito')::numeric(4,0),
        (r.payload->>'codigoprovinciadependenciacredito')::numeric(2,0),
        (r.payload->>'codigocantondependenciacredito')::numeric(2,0),
        (r.payload->>'tipocarteracrediticia')::numeric(2,0),
        (r.payload->>'tipoestadooperacioncrediticia')::numeric(3,0),
        (r.payload->>'diasmaximamorosidad')::numeric(4,0),
        (r.payload->>'montoformalizadooperacioncrediticia')::numeric(22,2),
        (r.payload->>'tipomonedaoperacion')::numeric(6,0),
        (r.payload->>'montooperacionautorizado')::numeric(22,2),
        (r.payload->>'cuentacontableprincipal')::numeric(15,0),
        (r.payload->>'saldoprincipaloperacioncrediticia')::numeric,
        (r.payload->>'cuentacontableprincipalcondepositoprevio')::numeric(15,0),
        (r.payload->>'saldoprincipalcondepositoprevio')::numeric(22,2),
        (r.payload->>'cuentacontableproductosporcobrar')::numeric(15,0),
        (r.payload->>'saldoproductosporcobrar')::numeric(22,2),
        (r.payload->>'cuentacontablepordesembolsarconcompromiso')::numeric(15,0),
        (r.payload->>'saldopordesembolsarconcompromiso')::numeric(22,2),
        (r.payload->>'cuentacontablecomisiones')::numeric(15,0),
        (r.payload->>'saldocomisionesoperacionescontingentes')::numeric(22,2),
        (r.payload->>'cuentacontablesaldopendienteutilizacionsincompromiso')::numeric(15,0),
        (r.payload->>'saldopendienteutilizacionsincompromiso')::numeric(22,2),
        (r.payload->>'montodesembolsado')::numeric(22,2),
        (r.payload->>'fechaformalizacion')::date,
        (r.payload->>'fechavencimiento')::date,
        (r.payload->>'ead')::numeric(22,2),
        (r.payload->>'saldooperacionsegmentacion')::numeric(22,2),
        (r.payload->>'tipofrecuenciapagoactualprincipal')::numeric(2,0),
        (r.payload->>'tipofrecuenciapagoactualintereses')::numeric(2,0),
        (r.payload->>'fechavencimientoperiodograciaprincipal')::date,
        (r.payload->>'tasaley7472')::numeric(10,7),
        (r.payload->>'tasainteresnominalvigente')::numeric(5,2),
        r.payload->>'indicadortipotasa',
        r.payload->>'factordetiempocalculointereses',
        r.payload->>'indicadorformapagovigenteprincipal',
        r.payload->>'indicadorformapagovigenteintereses',
        (r.payload->>'fechacorteoperacion')::date,
        (r.payload->>'fechaproximopagoprincipal')::date,
        (r.payload->>'fechaproximopagointereses')::date,
        (r.payload->>'fechaamortizacionhasta')::date,
        (r.payload->>'fechaintereshasta')::date,
        (r.payload->>'fechapagopactadoprincipal')::date,
        (r.payload->>'fechapagopactadointereses')::date,
        (r.payload->>'plazooperaciondias')::numeric(6,0),
        (r.payload->>'tipocuotaprincipal')::numeric(2,0),
        (r.payload->>'montocuotaprincipalactual')::numeric(22,2),
        (r.payload->>'montocuotainteresesactual')::numeric(22,2),
        r.payload->>'indicadoroperacionnueva',
        (r.payload->>'montorecuperacionprincipal')::numeric(22,2),
        (r.payload->>'montootrosaumentosdeprincipal')::numeric(22,2),
        (r.payload->>'montootrasdisminucionesdeprincipal')::numeric(22,2),
        r.payload->>'indicadorbacktoback',
        r.payload->>'indicadorcreditosindicado',
        r.payload->>'indicadoroperacionespecial',
        (r.payload->>'tipomotivooperacionespecial')::numeric(3,0),
        (r.payload->>'codigoclausulalimitecredito')::numeric(2,0),
        (r.payload->>'fechacambiotipotasa')::date,
        (r.payload->>'tipofrecuenciaajustetasainteresvariable')::numeric(2,0),
        (r.payload->>'tipoparametroreferenciatasainteresvariable')::numeric(3,0),
        (r.payload->>'porcentajecomponentevariabletasainteresvariable')::numeric(5,2),
        (r.payload->>'porcentajecomponentefijotasainteresvariable')::numeric(5,2),
        (r.payload->>'limiteinferiortasainteresvariable')::numeric(5,2),
        (r.payload->>'limitesuperiortasainteresvariable')::numeric(5,2),
        (r.payload->>'montoestimacionespecifica')::numeric(22,2),
        (r.payload->>'montoestimacionavales')::numeric(22,2),
        (r.payload->>'tipoprogramaautorizadosbd')::numeric(5,0),
        (r.payload->>'indicadorcreditogrupalsolidariosbd')::numeric(1,0),
        (r.payload->>'tiposectorprioritariodeudorsbd')::numeric(2,0),
        r.payload->>'idfondeadorsbd',
        (r.payload->>'tipopersonaidfondeadorsbd')::numeric(2,0),
        r.payload->>'indicadoroperacioncedidaengarantia',
        (r.payload->>'porcentajeponderadorspd')::numeric(5,2),
        (r.payload->>'porcentajeponderadorspc')::numeric(5,2),
        (r.payload->>'porcentajeindicadorltv')::numeric(5,2),
        r.payload->>'indicadorcambioclimatico',
        (r.payload->>'tipoclasificacionriesgoclimatico')::numeric(2,0),
        (r.payload->>'tipometodologiaclimatica')::numeric(2,0),
        (r.payload->>'tipopotencialidadimpactoclimatico')::numeric(2,0),
        NOW(),
        NOW()
    FROM fegusconfig.fe_ingestion_operaciones_raw r
    WHERE r.id_cliente = p_id_cliente
      AND r.id_load    = p_id_load
    ON CONFLICT (id_cliente, id_load, session_id, idoperacioncredito)
        DO UPDATE SET
            tipooperacionsfn                            = EXCLUDED.tipooperacionsfn,
            tipopersonadeudor                           = EXCLUDED.tipopersonadeudor,
            iddeudor                                    = EXCLUDED.iddeudor,
            idlineacredito                              = EXCLUDED.idlineacredito,
            indicadoroperacionmodificada                = EXCLUDED.indicadoroperacionmodificada,
            indicadorpresentacodeudores                 = EXCLUDED.indicadorpresentacodeudores,
            tipoenfoque                                 = EXCLUDED.tipoenfoque,
            tiposegmento                                = EXCLUDED.tiposegmento,
            codigoetapa                                 = EXCLUDED.codigoetapa,
            codigocategoriariesgo                       = EXCLUDED.codigocategoriariesgo,
            tasaincumplimiento                          = EXCLUDED.tasaincumplimiento,
            lgdminimocombinado                          = EXCLUDED.lgdminimocombinado,
            lgdpromedio                                 = EXCLUDED.lgdpromedio,
            lgdregulatorio                              = EXCLUDED.lgdregulatorio,
            tipooperacion                               = EXCLUDED.tipooperacion,
            tipocatalogosugef                           = EXCLUDED.tipocatalogosugef,
            codigopaisdestinocredito                    = EXCLUDED.codigopaisdestinocredito,
            codigoprovinciadestinocredito               = EXCLUDED.codigoprovinciadestinocredito,
            codigocantondestinocredito                  = EXCLUDED.codigocantondestinocredito,
            codigodistritodestinocredito                = EXCLUDED.codigodistritodestinocredito,
            codigoprovinciadependenciacredito           = EXCLUDED.codigoprovinciadependenciacredito,
            codigocantondependenciacredito              = EXCLUDED.codigocantondependenciacredito,
            tipocarteracrediticia                       = EXCLUDED.tipocarteracrediticia,
            tipoestadooperacioncrediticia               = EXCLUDED.tipoestadooperacioncrediticia,
            diasmaximamorosidad                         = EXCLUDED.diasmaximamorosidad,
            montoformalizadooperacioncrediticia         = EXCLUDED.montoformalizadooperacioncrediticia,
            tipomonedaoperacion                         = EXCLUDED.tipomonedaoperacion,
            montooperacionautorizado                    = EXCLUDED.montooperacionautorizado,
            cuentacontableprincipal                     = EXCLUDED.cuentacontableprincipal,
            saldoprincipaloperacioncrediticia           = EXCLUDED.saldoprincipaloperacioncrediticia,
            cuentacontableprincipalcondepositoprevio    = EXCLUDED.cuentacontableprincipalcondepositoprevio,
            saldoprincipalcondepositoprevio             = EXCLUDED.saldoprincipalcondepositoprevio,
            cuentacontableproductosporcobrar            = EXCLUDED.cuentacontableproductosporcobrar,
            saldoproductosporcobrar                     = EXCLUDED.saldoproductosporcobrar,
            cuentacontablepordesembolsarconcompromiso   = EXCLUDED.cuentacontablepordesembolsarconcompromiso,
            saldopordesembolsarconcompromiso            = EXCLUDED.saldopordesembolsarconcompromiso,
            cuentacontablecomisiones                    = EXCLUDED.cuentacontablecomisiones,
            saldocomisionesoperacionescontingentes      = EXCLUDED.saldocomisionesoperacionescontingentes,
            cuentacontablesaldopendienteutilizacionsincompromiso = EXCLUDED.cuentacontablesaldopendienteutilizacionsincompromiso,
            saldopendienteutilizacionsincompromiso      = EXCLUDED.saldopendienteutilizacionsincompromiso,
            montodesembolsado                           = EXCLUDED.montodesembolsado,
            fechaformalizacion                          = EXCLUDED.fechaformalizacion,
            fechavencimiento                            = EXCLUDED.fechavencimiento,
            ead                                         = EXCLUDED.ead,
            saldooperacionsegmentacion                  = EXCLUDED.saldooperacionsegmentacion,
            tipofrecuenciapagoactualprincipal           = EXCLUDED.tipofrecuenciapagoactualprincipal,
            tipofrecuenciapagoactualintereses           = EXCLUDED.tipofrecuenciapagoactualintereses,
            fechavencimientoperiodograciaprincipal      = EXCLUDED.fechavencimientoperiodograciaprincipal,
            tasaley7472                                 = EXCLUDED.tasaley7472,
            tasainteresnominalvigente                   = EXCLUDED.tasainteresnominalvigente,
            indicadortipotasa                           = EXCLUDED.indicadortipotasa,
            factordetiempocalculointereses              = EXCLUDED.factordetiempocalculointereses,
            indicadorformapagovigenteprincipal          = EXCLUDED.indicadorformapagovigenteprincipal,
            indicadorformapagovigenteintereses          = EXCLUDED.indicadorformapagovigenteintereses,
            fechacorteoperacion                         = EXCLUDED.fechacorteoperacion,
            fechaproximopagoprincipal                   = EXCLUDED.fechaproximopagoprincipal,
            fechaproximopagointereses                   = EXCLUDED.fechaproximopagointereses,
            fechaamortizacionhasta                      = EXCLUDED.fechaamortizacionhasta,
            fechaintereshasta                           = EXCLUDED.fechaintereshasta,
            fechapagopactadoprincipal                   = EXCLUDED.fechapagopactadoprincipal,
            fechapagopactadointereses                   = EXCLUDED.fechapagopactadointereses,
            plazooperaciondias                          = EXCLUDED.plazooperaciondias,
            tipocuotaprincipal                          = EXCLUDED.tipocuotaprincipal,
            montocuotaprincipalactual                   = EXCLUDED.montocuotaprincipalactual,
            montocuotainteresesactual                   = EXCLUDED.montocuotainteresesactual,
            indicadoroperacionnueva                     = EXCLUDED.indicadoroperacionnueva,
            montorecuperacionprincipal                  = EXCLUDED.montorecuperacionprincipal,
            montootrosaumentosdeprincipal               = EXCLUDED.montootrosaumentosdeprincipal,
            montootrasdisminucionesdeprincipal          = EXCLUDED.montootrasdisminucionesdeprincipal,
            indicadorbacktoback                         = EXCLUDED.indicadorbacktoback,
            indicadorcreditosindicado                   = EXCLUDED.indicadorcreditosindicado,
            indicadoroperacionespecial                  = EXCLUDED.indicadoroperacionespecial,
            tipomotivooperacionespecial                 = EXCLUDED.tipomotivooperacionespecial,
            codigoclausulalimitecredito                 = EXCLUDED.codigoclausulalimitecredito,
            fechacambiotipotasa                         = EXCLUDED.fechacambiotipotasa,
            tipofrecuenciaajustetasainteresvariable     = EXCLUDED.tipofrecuenciaajustetasainteresvariable,
            tipoparametroreferenciatasainteresvariable  = EXCLUDED.tipoparametroreferenciatasainteresvariable,
            porcentajecomponentevariabletasainteresvariable = EXCLUDED.porcentajecomponentevariabletasainteresvariable,
            porcentajecomponentefijotasainteresvariable = EXCLUDED.porcentajecomponentefijotasainteresvariable,
            limiteinferiortasainteresvariable           = EXCLUDED.limiteinferiortasainteresvariable,
            limitesuperiortasainteresvariable           = EXCLUDED.limitesuperiortasainteresvariable,
            montoestimacionespecifica                   = EXCLUDED.montoestimacionespecifica,
            montoestimacionavales                       = EXCLUDED.montoestimacionavales,
            tipoprogramaautorizadosbd                   = EXCLUDED.tipoprogramaautorizadosbd,
            indicadorcreditogrupalsolidariosbd          = EXCLUDED.indicadorcreditogrupalsolidariosbd,
            tiposectorprioritariodeudorsbd              = EXCLUDED.tiposectorprioritariodeudorsbd,
            idfondeadorsbd                              = EXCLUDED.idfondeadorsbd,
            tipopersonaidfondeadorsbd                   = EXCLUDED.tipopersonaidfondeadorsbd,
            indicadoroperacioncedidaengarantia          = EXCLUDED.indicadoroperacioncedidaengarantia,
            porcentajeponderadorspd                     = EXCLUDED.porcentajeponderadorspd,
            porcentajeponderadorspc                     = EXCLUDED.porcentajeponderadorspc,
            porcentajeindicadorltv                      = EXCLUDED.porcentajeindicadorltv,
            indicadorcambioclimatico                    = EXCLUDED.indicadorcambioclimatico,
            tipoclasificacionriesgoclimatico            = EXCLUDED.tipoclasificacionriesgoclimatico,
            tipometodologiaclimatica                    = EXCLUDED.tipometodologiaclimatica,
            tipopotencialidadimpactoclimatico           = EXCLUDED.tipopotencialidadimpactoclimatico,
            updated_at_utc                              = NOW();

    GET DIAGNOSTICS v_qty = ROW_COUNT;
    pqty       := v_qty;
    psqlcode   := '00000';
    psqlmessage := 'OK';
    RETURN NEXT;
EXCEPTION WHEN OTHERS THEN
    pqty       := 0;
    psqlcode   := SQLSTATE;
    psqlmessage := SQLERRM;
    RETURN NEXT;
END;
$$;
