CREATE TABLE feguslocal.bienesrealizables (
    id_load_local bigint NOT NULL,
    tipoadquisicionbien character varying(10) NOT NULL,
    idbienrealizable character varying(50) NOT NULL,
    indicadorgarantia character varying(1) NOT NULL,
    idgarantia character varying(50) NOT NULL,
    idbien character varying(50) NOT NULL,
    tipobien character varying(10) NOT NULL,
    fechaadjudicaciondacionbien date NOT NULL,
    saldoregistrocontable numeric(18,2) NOT NULL,
    tipomonedasaldoregistrocontable character varying(5) NOT NULL,
    cuentacatalogosugef character varying(50) NOT NULL,
    tipocatalogosugef character varying(10) NOT NULL,
    fechaultimatasacionbien date NOT NULL,
    montoultimatasacion numeric(18,2) NOT NULL,
    tipomonedamontoavaluo character varying(5) NOT NULL,
    tipopersonatasador character varying(2) NOT NULL,
    idtasador character varying(50) NOT NULL,
    tipopersonaempresatasadora character varying(2) NOT NULL,
    idempresatasadora character varying(50) NOT NULL,
    saldocontablecreditocancelado numeric(18,2) NOT NULL,
    tipomonedasaldocontablecreditocancelado character varying(5) NOT NULL,
    montoestimacion numeric(18,2) NOT NULL,
    created_at_utc timestamp without time zone DEFAULT now() NOT NULL,
    updated_at_utc timestamp without time zone
);
