CREATE TABLE feguslocal.cuentasporcobrarnosasociadas (
    id_load_local bigint NOT NULL,
    idoperacioncredito character varying(50) NOT NULL,
    tipopersonadeudor character varying(2) NOT NULL,
    idpersona character varying(50) NOT NULL,
    tipomonedamonto character varying(5) NOT NULL,
    montooriginal numeric(18,2) NOT NULL,
    tipocatalogosugef character varying(10) NOT NULL,
    cuentacontablesaldoprincipal character varying(50) NOT NULL,
    saldoprincipal numeric(18,2) NOT NULL,
    cuentacontablesaldoproductosporcobrar character varying(50) NOT NULL,
    saldoproductosporcobrar numeric(18,2) NOT NULL,
    fecharegistrocontable date NOT NULL,
    fechaexigibilidad date NOT NULL,
    fechavencimiento date NOT NULL,
    montoestimacionregistrada numeric(18,2) NOT NULL,
    tipodependencia character varying(10) NOT NULL,
    diasmora integer NOT NULL,
    created_at_utc timestamp without time zone DEFAULT now() NOT NULL,
    updated_at_utc timestamp without time zone
);
