CREATE TABLE feguslocal.garantiasvalores (
    id_load_local bigint NOT NULL,
    idgarantiavalor character varying(25) NOT NULL,
    tipoclasificacioninstrumento numeric(1,0) NOT NULL,
    tipopersona numeric(2,0),
    idemisor character varying(30),
    idinstrumento character varying(25) NOT NULL,
    serieinstrumento character varying(20),
    premio numeric(9,6),
    codigoisin character varying(25) NOT NULL,
    tipoasignacioncalificacion numeric(1,0) NOT NULL,
    categoriacalificacion numeric(1,0),
    codigocalificacionriesgo character varying(30),
    codigoempresacalificadora numeric(2,0),
    valorfacial numeric(20,2),
    tipomonedavalorfacial numeric(6,0),
    valormercado numeric(20,2) NOT NULL,
    tipomonedavalormercado numeric(6,0),
    fechaconstitucion date NOT NULL,
    fechavencimiento date,
    tipocolateralfinanciero numeric(2,0) NOT NULL,
    codigocalificacioninstrumento numeric(2,0) NOT NULL,
    porcentajeajusterc numeric(5,2) NOT NULL,
    created_at_utc timestamp without time zone DEFAULT now() NOT NULL,
    updated_at_utc timestamp without time zone
);
