CREATE TABLE feguslocal.garantiasoperacion (
    id_load_local bigint NOT NULL,
    tipopersonadeudor character varying(2) NOT NULL,
    iddeudor character varying(50) NOT NULL,
    idoperacioncredito character varying(50) NOT NULL,
    tipogarantia character varying(10) NOT NULL,
    idgarantia character varying(50) NOT NULL,
    indicadorformatraspasobien character varying(1) NOT NULL,
    idgarantiatraspaso character varying(50) NOT NULL,
    tipomitigador character varying(10) NOT NULL,
    tipodocumentolegal character varying(10) NOT NULL,
    valorajustadogarantia numeric(18,2) NOT NULL,
    tipoinscripciongarantia character varying(10) NOT NULL,
    porcentajeresponsabilidadgarantia numeric(5,2) NOT NULL,
    valornominalgarantia numeric(18,2) NOT NULL,
    fechapresentacionregistrogarantia date,
    tipomonedavalornominalgarantia character varying(5),
    fechaconstituciongarantia date,
    fechavencimientogarantia date,
    created_at_utc timestamp without time zone DEFAULT now() NOT NULL,
    updated_at_utc timestamp without time zone
);
